language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Aqz6squMI7uyWg8L1ppd5lW3jO9K81C42XxuFCPeeTmgEgc1YFDFYJib0Y5+nhwGSPlGedEw5wYvLlWB/jm/dpyP2SHeUbPvlnnUEUHQ5Wq6l0qWZCH3FlP+B1hWsSj1D8p7UmWolqOERD8w4USphw0rTDogWV7/MLp4DrNYBBm2Vge6YBlZRg1tLxu9HrEu+SRiY6I9iLM84gxSRwbASxyeHsVHB/M277X06uoD2njkiEg3k40I926hRADL1wu/YqOrA/I0q5RYn+2tfKrcNF63YAF0Zrkc785qvrHjWSF0e9I/d0Q5zqLfybDpMygIT1TrUmXy09LhbTECPJbNP8Dy6BhiD0HyoiZVxRLxyJbwMDXoodFUx6f9Zk1fxZE+B036KR/8pOyTmkvJf/5y/kVWkVWpYBZjXo9CSaDbqCKn85G5ebrwdGK4U/VF56CdLu+Fx24fjzFD6lbK3TpUXdEt0etgRh3sjmwOetY+9RDN9Yb9qJX8Du9/r1W7WuUYKoJxJ3JzEsgHve3+UzTQsO61Wv0WK9eALdHb4foNPtdqM0Xav7wnOZNkgFe1HaqyWLrM2wDRdQWiZyXwKE62/2BxgV+NYEBHhOinOwyEbQe0FDKUu0SzVc+02XxvxTbtz/SWBdCnv0fA5vXvw6z1ebO4z17sE6fNJ0ELoCKsDIw=
  app: nameless-inlet-97185
  on:
    repo: MissyM2/efu-client
